es:
  only:
    - 'master'

language: ruby

rvm:
  - 2.3.1

script: bundle exec rspec spec

script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
  - bundle exec rake db:seed_fu
  - bundle exec rake test
